config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "users#index"

  resources :users do
    resources :holidays
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  
  ## Обработка state_machine
  include AASM

  aasm do
    state :being_reviewed, display: 'На рассмотрении'
    state :accepted, display: 'Принято'
    state :rejected, display: 'Отказано'
   
    event :accept do
      transitions from: :being_reviewed, to: :accepted
    end

    event :reject do
      transitions from: :being_reviewed, to: :rejected
    end
  end

  belongs_to :user 

  ## Сортировка дат отпуска
  default_scope { order(date_start: :desc, aasm_state: :asc)}

  ##

  def username
    self.user.username
  end

  ## Валидация дат отпуска

  validates_presence_of :date_start, :date_end
  
  validates :date_end, comparison: { greater_than_or_equal_to: :date_start }

  scope :date_validation, -> (date_end, date_start) { where("(date_start <= ? and ? <= date_end and aasm_state = 'being_reviewed') or (date_start <= ? and ? <= date_end and aasm_state = 'accepted')", date_end, date_start, date_end, date_start )}

  # scope :date_validation_two, -> (date_end, date_start) { where("date_start <= ? and ? <= date_end and aasm_state = 'accepted'", date_end, date_start )}

  scope :date_validation_being_reviewed, -> (date_start, date_end) { where("date_start = ? and date_end = ? and aasm_state = 'being_reviewed'", date_start, date_end)}

  include ActiveModel::Validations
  validates_with ValidateDate, on: :create
  # byebug
end

app/models/user.rb
class User < ApplicationRecord
  has_many :holidays, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/validate_date.rb
class ValidateDate < ActiveModel::Validator

  def validate(holiday)
    
    if  Holiday.date_validation_being_reviewed(holiday.date_start, holiday.date_end) != []  
      holiday.errors.add :base, :invalid, message: "Ошибка: указанные даты пересекаются с датами, принятыми к рассмотрению."
    elsif Holiday.date_validation(holiday.date_end, holiday.date_start) != [] 
      holiday.errors.add :base, :invalid, message: "Ошибка: указанные даты пересекаются с уже согласованными датами."
    end
    # byebug
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @user = User.find(params[:user_id])
    @holiday =  @user.holidays.new(holiday_params)
    
    if @holiday.save
      redirect_to user_path(@user)
      flash[:notice] = "Запись отправлена для согласования"
    else
      render user_path(:show)  
    end
  end
  
  private
    def holiday_params
      params.require(:holiday).permit(:date_start, :date_end)
    end
end

app/controllers/rails_admin_controller.rb
class RailsAdminController < ActionController::Base
  
  around_action :switch_locale

  private

  def switch_locale(&action)
    I18n.with_locale(:ru, &action) # or anything you like
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  
  def index
    @users = User.all
    # @users = User.joins(:holidays).all

    if current_user.admin?
     redirect_to "/admin"
    else
      redirect_to "/users/#{current_user.id}"
    end
  end
 
  def show
    @user = User.find(params[:id])
    @holiday = @user.holidays.new
    if current_user.admin?
      redirect_to "/admin"
    end
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end

private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-info">
  <head>
    <title>Holidays</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_form.html.erb
<%= form_with model: @user do |form| %>
  <div>
    <% form.label :username %>Ваше имя<br>
    <%= form.text_field :username %>
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <% form.label :password %>Пароль<br>
    <%= form.text_field :password %><br>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit "Создать сотрудника"%>
  </div>
<% end %>

app/views/users/index.html.erb
  <% if user_signed_in? && current_user.admin = true%>
    <span>Здравствуйте, <%= current_user.email %>, <%= current_user.id %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>

     <h2>Сотрудники</h2>

     <ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to  user.username, user %> 
      
      <% user.holidays.each do |holiday| %>
  <p>
    <%= l(holiday.date_start, format: ("%d-%m-%Y") ) %> - <%= l(holiday.date_end, format: ("%d-%m-%Y"))%>
  </p>

<% end %>
</li>
      <% end %>
</ul>
<br>
<%= link_to "Новый сотрудник", new_user_path %>
<br>
<br>
<% if @users.size > 1 %>
  <%= link_to "Удалить сотрудника", user_path(@users[-1]), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
  } %>
<% elsif @users.size == 1%>
   <%= link_to "Удалить сотрудника", user_path(@users[0]), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
  } %>
  <%else%>
<% end %>
<br>
<br>
<%= link_to "Админ-панель", rails_admin_path %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

app/views/users/new.html.erb
<h1>Новый сотрудник</h1>

<%= render 'partials/form', form: @form %>

<%= link_to "На главную", root_path %>

app/views/users/show.html.erb
<div class="bg-info">
  <% if user_signed_in? %>
  <div class="container">
    <div class="row py-2">
      <div class="col">
        <p>Приложение DayOff v 0.5</p>
      </div>
    </div>

    <div class="row mb-4">
      <div class="col">
        <span class="me-2">Здравствуйте, <%= current_user.username %></span>
        <span class="link-logout"><%= link_to "Выйти", destroy_user_session_path, :method => :delete, class: "link-logout" %></span>
      </div>
    </div>
   
    <div class="row mb-3 bg-light">
      <div class="col bg-light p-4 border-end"> 
        <h2 class="mb-4"> Добавить запись: </h2>
        <%= turbo_frame_tag "user" d %> <%# для отображения ошибок внутри формы при непрохождении валидации%>
        <%= form_with model: [@user, @user.holidays.new] do |form| %>
        <div class="row">
          <div class="col">
            <p>
              <% form.label :date_start %>Начало отпуска<br><br>
              <%= form.date_field :date_start, :required => true, min: Date.today, max: Date.today + 365, class: "w-100" %>
            </p>
          </div>
          <div class="col">
            <p>
              <% form.label :date_end %>Конец отпуска<br><br>
              <%= form.date_field :date_end, :required => true, min: Date.today, max: Date.today + 365, class: "w-100" %>
            </p>
          </div>
          <p>
            <%= form.submit "Добавить запись", class:"btn btn-info text-light align-item-center w-100"%> 
          </p>
 
          <% @holiday.errors.full_messages.each do |message| %>
            <p class="bg-danger text-white p-3 w-100"><%= message %></p>
          <% end %>
 
          <% flash.each do |type, msg| %>
            <p class="alert alert-info w-100">
              <%= msg %>
            </p>
          <% end %>
        </div>
        <% end %>
        <% end %>
      </div>
   
      <div class="col bg-light py-4 px-4 border-start">
        <h2 class="mb-4"> Мои данные </h2>
        <span> E - mail: <%= @user.email %> </p>
      </div> 
    </div> 
  


    <div class="row bg-light">
      <div class="col bg-light py-5 px-5">
        <h2 class="mb-4">Даты отпуска</h2>
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th scope="col">Номер записи</th>
              <th scope="col">Начало отпуска</th>
              <th scope="col">Конец отпуска</th>
              <th scope="col">Статус заявки</th>
            </tr>
          </thead>
          <tbody>
             <% @user.holidays.each_with_index do |holiday, index| %>
              <% if holiday.date_start == nil && holiday.date_end == nil %>
              <% else %>
            <tr>
            <td> <%= index += 1 %></td>
            <td><%= l(holiday.date_start, format: ("%d.%m.%Y")) %></td>
            <td><%= l(holiday.date_end, format: ("%d.%m.%Y")) %></td>
            <td><%= holiday.aasm.human_state %></td>
            </tr>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>  
</div>